### ISSUE TITLE
Unsupported pickle level on server

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/LibraryMetricScripts#28]
```
Loading data
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/local/NVMe2/home/sarah/Projects/LibraryMetricScripts/scripts/__main__.py", line 4, in <module>
    app.run()
  File "/local/NVMe2/home/sarah/Projects/LibraryMetricScripts/scripts/app.py", line 22, in run
    getLastModificationDates()
  File "/local/NVMe2/home/sarah/Projects/LibraryMetricScripts/scripts/LastModificationDate/lastmodificationdate.py", line 49, in getLastModificationDates
    data = loadLastModificationDateData()
  File "/local/NVMe2/home/sarah/Projects/LibraryMetricScripts/scripts/LastModificationDate/lastmodificationdate.py", line 36, in loadLastModificationDateData
    data = pickle.load(input)
ValueError: unsupported pickle protocol: 5
```

**Comment by snadi** [comment]
Addressed in PR #24 by using DEFAULT protocol level instead of HIGHEST_LEVEL
