### ISSUE TITLE
Breaking changes fails on some releases

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/LibraryMetricScripts#44]
Example:

```
Calculating for  rel/commons-lang-3.12.0
Exception in thread "main" java.lang.NullPointerException
	at EnumDeclarationVisitor.isConsiderable(EnumDeclarationVisitor.java:19)
	at EnumDeclarationVisitor.visit(EnumDeclarationVisitor.java:33)
	at org.eclipse.jdt.core.dom.EnumDeclaration.accept0(EnumDeclaration.java:274)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:212)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at APIVersion.parse(APIVersion.java:75)
	at APIVersion.parseFilesInDir(APIVersion.java:39)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.<init>(APIVersion.java:30)
	at MainCounter.main(MainCounter.java:12)
Skipping release LibraryRelease object (3068)
b''
Calculating for  commons-lang-3.12.0-RC1
Exception in thread "main" java.lang.NullPointerException
	at EnumDeclarationVisitor.isConsiderable(EnumDeclarationVisitor.java:19)
	at EnumDeclarationVisitor.visit(EnumDeclarationVisitor.java:33)
	at org.eclipse.jdt.core.dom.EnumDeclaration.accept0(EnumDeclaration.java:274)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:212)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at APIVersion.parse(APIVersion.java:75)
	at APIVersion.parseFilesInDir(APIVersion.java:39)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.parseFilesInDir(APIVersion.java:43)
	at APIVersion.<init>(APIVersion.java:30)
	at MainCounter.main(MainCounter.java:12)
Skipping release LibraryRelease object (3069)
b''
```

**Comment by snadi** [comment]
Right now, we catch those exceptions and proceed. However, since nothing gets stored in the DB, every time we re-run the scripts, it attempts to recalulate them. It might be better to store a -1 in DB or something and when calculating average, these -1 values are skipped.
